services:
    web:
        networks:
            - app_network
        container_name: web
        build:
            network: host
            context: .
            dockerfile: ./.deploy/web/Dockerfile
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - admin_panel
        environment:
            - CMS_BASE_ENDPOINT=http://admin_panel:4000

    admin_panel:
        networks:
            - app_network
        container_name: admin_panel
        build:
            context: .
            network: host
            dockerfile: ./.deploy/admin-panel/Dockerfile
        restart: always
        ports:
            - 4000:4000
        depends_on:
            - mongo

    mongo:
        networks:
            - app_network
        image: mongo:6-jammy
        ports:
            - 27017:27017
        volumes:
            - database:/data/db

volumes:
    database:
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    app_network:
        driver: bridge
