version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app_network
    depends_on:
      - admin_panel
    env_file: 
      - ./apps/web/.env.production

  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: ./apps/admin-panel/Dockerfile
    restart: always
    ports:
      - '4000:4000'
    networks:
      - app_network
    depends_on:
      - mongo
    env_file:
      - ./apps/admin-panel/.env

  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      -   database:/data/db
    networks:
      - app_network

volumes:
  database:
  

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
