import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getFooter, getHeader } from '@requests'
import '@repo/ui/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}): Promise<Promise<JSX.Element>> {
    const footerData = await getFooter()
    const headerData = await getHeader()

    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>{JSON.stringify(headerData, null, 4)}</nav>
                {children}
                <footer>{JSON.stringify(footerData, null, 4)}</footer>
            </body>
        </html>
    )
}
