steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '-t'
          - 'gcr.io/bytevertize/github.com/bytevertize/base:$COMMIT_SHA'
          - '-f'
          - .deploy/web/Dockerfile
          - .
          - '--build-arg'
          - NEXT_PUBLIC_PAYLOAD_ENDPOINT=${_NEXT_PUBLIC_PAYLOAD_ENDPOINT}
          - '--build-arg'
          - GRAPHQL_ENDPOINT=${_GRAPHQL_ENDPOINT}
          - '--build-arg'
          - NEXT_PUBLIC_LANG_COOKIE=${_NEXT_PUBLIC_LANG_COOKIE}
          - '--build-arg'
          - PAYLOAD_DRAFT_TOKEN=$$PAYLOAD_DRAFT_TOKEN
          - '--build-arg'
          - PAYLOAD_HOSTNAME=${_PAYLOAD_HOSTNAME}
      id: Build
      secretEnv:
          - PAYLOAD_DRAFT_TOKEN
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - 'gcr.io/bytevertize/github.com/bytevertize/base:$COMMIT_SHA'
      id: Push
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - '--platform=managed'
          - '--image=gcr.io/bytevertize/github.com/bytevertize/base:$COMMIT_SHA'
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
          - '--region=$_DEPLOY_REGION'
          - '--quiet'
      id: Deploy
      entrypoint: gcloud
images:
    - 'gcr.io/bytevertize/github.com/bytevertize/base:$COMMIT_SHA'
options:
    substitutionOption: ALLOW_LOOSE
    automapSubstitutions: true
substitutions:
    _GRAPHQL_ENDPOINT: DEFAULT
    _NEXT_PUBLIC_PAYLOAD_ENDPOINT: DEFAULT
    _NEXT_PUBLIC_LANG_COOKIE: DEFAULT
    _DEPLOY_REGION: europe-west1
    _AR_HOSTNAME: europe-west1-docker.pkg.dev
    _SERVICE_NAME: web-test
    _PLATFORM: managed
    _PAYLOAD_HOSTNAME: DEFAULT
availableSecrets:
    secretManager:
        - versionName: >-
              projects/bytevertize/secrets/PAYLOAD_PUBLIC_WEB_DRAFT_TOKEN/versions/latest
          env: PAYLOAD_DRAFT_TOKEN
