import '../globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import '@repo/ui/styles.css'
import { RootLayout as AppRootLayout } from '@components'

const font = Raleway({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}): JSX.Element {
    return <AppRootLayout font={font}>{children}</AppRootLayout>
}
