import '../../globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import '@repo/ui/styles.css'
import type { Locale } from '@i18n/types'
import { RootLayout as AppRootLayout } from '@components/index'
import { getFooter, getHeader } from '@requests'

const font = Raleway({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

export default async function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode
    params: {
        locale: Locale
    }
}) {
    const { Footer: footerData } = await getFooter({ locale, draft: false })
    const { Header: headerData } = await getHeader({ locale, draft: false })

    return (
        <AppRootLayout
            font={font}
            footerData={footerData}
            headerData={headerData}
            locale={locale}
        >
            {children}
        </AppRootLayout>
    )
}

export function generateStaticParams(): { locale: Locale }[] {
    return [{ locale: 'en' }, { locale: 'bg' }]
}
