import '../../globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import '@repo/ui/styles.css'
import type { Locale } from '@i18n/types'
import { RootLayout as AppRootLayout } from '@components/index'

const font = Raleway({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode
    params: {
        locale: Locale
    }
}): JSX.Element {
    return (
        <AppRootLayout font={font} locale={locale}>
            {children}
        </AppRootLayout>
    )
}

export function generateStaticParams(): { locale: Locale }[] {
    return [{ locale: 'en' }, { locale: 'bg' }]
}
